import type { Product, ProductColor } from "@/types";

/**
 * Local product catalogue — the only data source for the storefront at launch.
 *
 * No backend yet: this array drives the home page, catalogue, product pages and
 * the cart. When a CMS / commerce API is introduced, replace these reads with
 * async fetchers but keep the `Product` shape (see `types/index.ts`) so the UI
 * doesn't have to change.
 *
 * Images are branded SVG placeholders generated by
 * `scripts/generate-placeholders.mjs`. Swap them for real product photography
 * in /public/products (one set per colour, ideally) without touching this file.
 */
export const products: Product[] = [
  {
    id: "core-logo-cap",
    name: "Кепка Core Logo",
    price: 2490,
    category: "caps",
    colors: [
      { name: "Чёрный", hex: "#141414" },
      { name: "Тёмно-синий", hex: "#1d2b45" },
      { name: "Бежево-зелёный", hex: "#8a8d6f" },
      { name: "Голубой", hex: "#9ec3d8" },
    ],
    sizes: ["One Size"],
    images: [
      "/products/core-logo-cap-1.svg",
      "/products/core-logo-cap-2.svg",
      "/products/core-logo-cap-3.svg",
    ],
    description:
      "Классическая шестипанельная кепка с низким профилем и вышитым логотипом STOAT. Структурированная тулья, изогнутый козырёк и металлическая застёжка с гравировкой. База гардероба в четырёх цветах сезона.",
    inStock: true,
    isNew: true,
  },
  {
    id: "field-cap",
    name: "Кепка Field",
    price: 2790,
    category: "caps",
    colors: [
      { name: "Бежево-зелёный", hex: "#8a8d6f" },
      { name: "Чёрный", hex: "#141414" },
    ],
    sizes: ["One Size"],
    images: [
      "/products/field-cap-1.svg",
      "/products/field-cap-2.svg",
      "/products/field-cap-3.svg",
    ],
    description:
      "Кепка в духе рабочей эстетики: мягкая неструктурированная тулья, удлинённый козырёк и хлопковая саржа с лёгким эффектом стирки. Тканевый ремешок с пряжкой для точной посадки.",
    inStock: true,
  },
  {
    id: "box-logo-tee",
    name: "Футболка Box Logo",
    price: 3490,
    category: "tshirts",
    colors: [
      { name: "Белый", hex: "#f4f3ee" },
      { name: "Чёрный", hex: "#161616" },
    ],
    sizes: ["S", "M", "L", "XL"],
    images: [
      "/products/box-logo-tee-1.svg",
      "/products/box-logo-tee-2.svg",
      "/products/box-logo-tee-3.svg",
    ],
    description:
      "Футболка прямого кроя из плотного хлопка 220 г/м² с фирменным box-логотипом на груди. Усиленный воротник, спущенное плечо и слегка удлинённый силуэт. Носится соло или слоями.",
    inStock: true,
    isNew: true,
  },
  {
    id: "heavyweight-tee",
    name: "Футболка Heavyweight",
    price: 3990,
    category: "tshirts",
    colors: [
      { name: "Молочный", hex: "#ece6da" },
      { name: "Графит", hex: "#2c2c2c" },
    ],
    sizes: ["S", "M", "L", "XL"],
    images: [
      "/products/heavyweight-tee-1.svg",
      "/products/heavyweight-tee-2.svg",
      "/products/heavyweight-tee-3.svg",
    ],
    description:
      "Тяжёлая футболка 260 г/м² из чёсаного хлопка с плотной структурой, которая держит форму. Минималистичный тональный принт-горностай на спине. Oversize-посадка.",
    inStock: true,
  },
  {
    id: "essential-hoodie",
    name: "Худи Essential",
    price: 7490,
    category: "hoodies",
    colors: [
      { name: "Чёрный", hex: "#161616" },
      { name: "Серый меланж", hex: "#9b9b9b" },
      { name: "Бежево-зелёный", hex: "#8a8d6f" },
    ],
    sizes: ["S", "M", "L", "XL"],
    images: [
      "/products/essential-hoodie-1.svg",
      "/products/essential-hoodie-2.svg",
      "/products/essential-hoodie-3.svg",
    ],
    description:
      "Базовое худи из французского футера 400 г/м² с двухслойным капюшоном и карманом-кенгуру. Мягкий начёс изнутри, рёбра с эластаном на манжетах. Главный кэжуал-слой STOAT.",
    inStock: true,
    isNew: true,
  },
  {
    id: "tonal-hoodie",
    name: "Худи Tonal",
    price: 7990,
    category: "hoodies",
    colors: [
      { name: "Кремовый", hex: "#e7dfcf" },
      { name: "Тёмно-синий", hex: "#1d2b45" },
    ],
    sizes: ["S", "M", "L", "XL"],
    images: [
      "/products/tonal-hoodie-1.svg",
      "/products/tonal-hoodie-2.svg",
      "/products/tonal-hoodie-3.svg",
    ],
    description:
      "Худи с тональной вышивкой логотипа тон-в-тон и потайной молнией на кармане. Плотный петлевой футер, слегка укороченная длина и объёмный крой. Спокойная роскошь без логомании.",
    inStock: false,
  },
  {
    id: "logo-socks",
    name: "Носки Logo (2 пары)",
    price: 990,
    category: "accessories",
    colors: [
      { name: "Белый", hex: "#f4f3ee" },
      { name: "Чёрный", hex: "#161616" },
    ],
    sizes: ["39–42", "43–46"],
    images: [
      "/products/logo-socks-1.svg",
      "/products/logo-socks-2.svg",
    ],
    description:
      "Набор из двух пар высоких носков из чёсаного хлопка с жаккардовым логотипом и усиленным мыском и пяткой. Рубчатая резинка надёжно держит. Комплект на каждый день.",
    inStock: true,
    isNew: true,
  },
  {
    id: "canvas-tote",
    name: "Сумка-шопер Canvas",
    price: 1990,
    category: "accessories",
    colors: [
      { name: "Натуральный", hex: "#d8cfba" },
      { name: "Чёрный", hex: "#161616" },
    ],
    sizes: ["One Size"],
    images: [
      "/products/canvas-tote-1.svg",
      "/products/canvas-tote-2.svg",
    ],
    description:
      "Плотная сумка-шопер из хлопкового канваса 380 г/м² с трафаретным логотипом, внутренним карманом и усиленными ручками. Держит форму и спокойно увозит покупки на неделю.",
    inStock: true,
  },
];

/** Find a single product by id (used by the product detail route). */
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

/** Products flagged as new arrivals for the home page section. */
export function getNewArrivals(): Product[] {
  const flagged = products.filter((p) => p.isNew);
  return flagged.length > 0 ? flagged : products.slice(0, 4);
}

/**
 * Up to `limit` other products in the same category — powers the
 * "Похожие товары" block on the product page.
 */
export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

/** Distinct colour options across the catalogue (for the shop filters). */
export function getColorOptions(): ProductColor[] {
  const seen = new Map<string, string>();
  for (const p of products) {
    for (const c of p.colors) {
      if (!seen.has(c.name)) seen.set(c.name, c.hex);
    }
  }
  return Array.from(seen, ([name, hex]) => ({ name, hex }));
}

// Preferred size ordering so chips read S → M → L → XL, then the rest.
const SIZE_ORDER = ["XS", "S", "M", "L", "XL", "XXL", "One Size"];

/** Distinct size options across the catalogue, in a sensible order. */
export function getSizeOptions(): string[] {
  const set = new Set<string>();
  for (const p of products) for (const s of p.sizes) set.add(s);
  return Array.from(set).sort((a, b) => {
    const ia = SIZE_ORDER.indexOf(a);
    const ib = SIZE_ORDER.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b, "ru");
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
}
